version: '3.12'
services:
  web:
    build: .
    command: ./wait-for-it.sh mysql:3306 -- ./docker-entrypoint.sh
    ports:
      - 8000:8000
    depends_on:
      - mysql
    restart: on-failure
    volumes:
      - .:/app

  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    restart: always
    environment:
      - MYSQL_DATABASE=django_omni_admin
      - MYSQL_ROOT_PASSWORD=marakha7057
    volumes:
      - mysqldata:/var/lib/mysql     

volumes:
  mysqldata:

