# Generated by Django 5.0.6 on 2024-05-29 19:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destination',
            options={'ordering': ['title']},
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nick_name', models.CharField(blank=True, max_length=255, null=True)),
                ('initial', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Initials must be 1-7 characters long and contain only uppercase letters and numbers.', regex='^[A-Z0-9]{1,7}$')])),
                ('address', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('A', 'Active'), ('D', 'Draft'), ('C', 'Coming Soon')], default='C', max_length=1)),
                ('logo', models.ImageField(upload_to='segment/images')),
                ('overview', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message='Enter a valid telephone number.', regex='^[+\\d][\\d]+$')])),
                ('mobile', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message='Enter a valid Bangladeshi mobile number.', regex='^\\+880?\\d{10}$|^0\\d{10}$')])),
                ('location_iframe', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='segment.destination')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
