# Generated by Django 5.0.6 on 2024-05-29 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segment', '0002_alter_destination_options_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='segment/images')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sliders', to='segment.branch')),
            ],
        ),
    ]
