# Generated by Django 5.0.6 on 2024-05-30 17:25

import django.db.models.deletion
import general_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segment', '0003_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='branch',
            name='logo',
            field=models.ImageField(upload_to='segment/images', validators=[general_app.validators.image_max_size]),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(upload_to='segment/images', validators=[general_app.validators.image_max_size]),
        ),
        migrations.CreateModel(
            name='BookSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slider_images/')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sliders', to='segment.book')),
            ],
        ),
    ]
