# Generated by Django 5.0.6 on 2024-05-30 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('segment', '0004_book_alter_branch_logo_alter_slider_image_bookslider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookslider',
            name='book',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookSlider',
        ),
    ]
