# Generated by Django 5.0.6 on 2024-06-06 14:33

import django.db.models.deletion
import general_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segment', '0005_remove_bookslider_book_delete_book_delete_bookslider'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='destination',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='segment/images', validators=[general_app.validators.image_max_size]),
        ),
        migrations.AlterField(
            model_name='branch',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='segment.destination'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='initial',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='branch',
            name='mobile',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='branch',
            name='telephone',
            field=models.CharField(max_length=14),
        ),
    ]
