# Generated by Django 5.0.6 on 2024-06-06 19:16

import django.db.models.deletion
import general_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segment', '0006_branchmanager_destination_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Draft', 'Draft'), ('Coming Soon', 'Coming Soon')], default='Coming Soon', max_length=15),
        ),
        migrations.CreateModel(
            name='BranchSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Single Video', 'Single Video'), ('Static Sliders', 'Static Sliders')], max_length=15)),
                ('featured_image', models.ImageField(upload_to='segment/images', validators=[general_app.validators.image_max_size])),
                ('video_slider_title', models.CharField(blank=True, max_length=255, null=True)),
                ('video_slider_subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('video_slider_button_one_title', models.CharField(blank=True, max_length=255, null=True)),
                ('video_slider_button_one_link', models.CharField(blank=True, max_length=255, null=True)),
                ('video_slider_button_two_title', models.CharField(blank=True, max_length=255, null=True)),
                ('video_slider_button_two_link', models.CharField(blank=True, max_length=255, null=True)),
                ('video_slider_youtube_link', models.CharField(blank=True, max_length=255, null=True)),
                ('static_slider_one_title', models.CharField(blank=True, max_length=255, null=True)),
                ('static_slider_one_subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('static_slider_one_button_one_title', models.CharField(blank=True, max_length=255, null=True)),
                ('static_slider_one_button_one_link', models.CharField(blank=True, max_length=255, null=True)),
                ('static_slider_one_button_two_title', models.CharField(blank=True, max_length=255, null=True)),
                ('static_slider_one_button_two_link', models.CharField(blank=True, max_length=255, null=True)),
                ('static_slider_one_image_link', models.ImageField(blank=True, null=True, upload_to='segment/images')),
                ('static_slider_two_title', models.CharField(blank=True, max_length=255, null=True)),
                ('static_slider_two_subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('static_slider_two_button_one_title', models.CharField(blank=True, max_length=255, null=True)),
                ('static_slider_two_button_one_link', models.CharField(blank=True, max_length=255, null=True)),
                ('static_slider_two_button_two_title', models.CharField(blank=True, max_length=255, null=True)),
                ('static_slider_two_button_two_link', models.CharField(blank=True, max_length=255, null=True)),
                ('static_slider_two_image_link', models.ImageField(blank=True, null=True, upload_to='segment/images')),
                ('static_slider_three_title', models.CharField(blank=True, max_length=255, null=True)),
                ('static_slider_three_subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('static_slider_three_button_one_title', models.CharField(blank=True, max_length=255, null=True)),
                ('static_slider_three_button_one_link', models.CharField(blank=True, max_length=255, null=True)),
                ('static_slider_three_button_two_title', models.CharField(blank=True, max_length=255, null=True)),
                ('static_slider_three_button_two_link', models.CharField(blank=True, max_length=255, null=True)),
                ('static_slider_three_image_link', models.ImageField(blank=True, null=True, upload_to='segment/images')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sliders', to='segment.branch')),
            ],
        ),
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
