# Generated by Django 5.0.6 on 2024-06-06 20:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segment', '0007_alter_branch_status_branchslider_delete_slider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branchslider',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='branchslider',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
