# Generated by Django 5.0.6 on 2024-06-06 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segment', '0009_alter_branchslider_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchslider',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sliders', to='segment.branch'),
        ),
    ]
