# Generated by Django 5.0.6 on 2024-06-06 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_guest_created_at_staff'),
        ('segment', '0010_alter_branchslider_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='segment.branch')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.staff')),
            ],
            options={
                'unique_together': {('branch', 'staff')},
            },
        ),
        migrations.DeleteModel(
            name='BranchManager',
        ),
    ]
