# Generated by Django 5.0.6 on 2024-06-08 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segment', '0013_alter_roomamenities_room_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomcategory',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Out Of Order', 'Out Of Order')], default='Out Of Order', max_length=15),
        ),
    ]
