# Generated by Django 5.0.6 on 2024-06-08 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('segment', '0015_room'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
