# Generated by Django 5.0.6 on 2024-06-08 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segment', '0017_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Out Of Order', 'Out Of Order')], default='Active', max_length=15),
        ),
    ]
