# Generated by Django 5.0.6 on 2024-06-12 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('segment', '0018_alter_room_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='roomcategory',
            unique_together={('room_name', 'branch')},
        ),
    ]
