# Generated by Django 5.0.6 on 2024-06-12 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('segment', '0019_alter_roomcategory_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('room_number', 'room_category')},
        ),
    ]
