# Generated by Django 5.0.6 on 2024-06-13 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_guest_created_at_staff'),
        ('segment', '0020_alter_room_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=14)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled'), ('Checked In', 'Checked In'), ('Checked Out', 'Checked Out')], default='Pending', max_length=15)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='community.guest')),
            ],
        ),
    ]
