# Generated by Django 5.0.6 on 2024-06-13 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segment', '0024_booking_placed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='billing',
            name='paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
