# Generated by Django 5.0.6 on 2024-06-27 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segment', '0029_alter_cartitem_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='segment.branch'),
            preserve_default=False,
        ),
    ]
