# Generated by Django 5.0.6 on 2024-07-02 09:39

import django.core.validators
import django.db.models.deletion
import general_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segment', '0030_booking_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='TouristSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('distance_from_hotel', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('featured_image', models.ImageField(upload_to='segment/images', validators=[general_app.validators.image_max_size])),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='segment.branch')),
            ],
        ),
    ]
