# Generated by Django 5.0.6 on 2024-07-02 09:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segment', '0031_touristspot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='touristspot',
            old_name='distance_from_hotel',
            new_name='distance_from_hotel_in_km',
        ),
        migrations.AddField(
            model_name='touristspot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
