# Generated by Django 5.0.6 on 2024-07-04 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segment', '0033_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='segment.roomcategory')),
            ],
        ),
    ]
