# Generated by Django 5.0.6 on 2024-07-04 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segment', '0034_favoriteroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriteroom',
            name='room_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='segment.roomcategory', unique=True),
        ),
    ]
