# Generated by Django 5.0.6 on 2024-07-04 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segment', '0035_alter_favoriteroom_room_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriteroom',
            name='room_category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='segment.roomcategory'),
        ),
    ]
