# Generated by Django 5.0.6 on 2024-07-04 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('segment', '0036_alter_favoriteroom_room_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FavoriteRoom',
            new_name='FavoriteRoomCategory',
        ),
    ]
