# Generated by Django 5.0.6 on 2024-07-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segment', '0037_rename_favoriteroom_favoriteroomcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured_image', models.ImageField(upload_to='segment/images')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
