# Generated by Django 5.0.6 on 2024-07-05 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('segment', '0038_offer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
