# Generated by Django 5.1 on 2024-09-01 17:36

import general_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segment', '0039_delete_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='segment/images', validators=[general_app.validators.image_max_size])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
