# Generated by Django 5.1 on 2024-09-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segment', '0040_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='check_in',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='check_out',
            field=models.DateField(blank=True, null=True),
        ),
    ]
