# Generated by Django 5.1 on 2024-10-19 15:29

import datetime
import segment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segment', '0041_cart_check_in_cart_check_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='check_in',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='cart',
            name='check_out',
            field=models.DateField(default=segment.models.default_check_out),
        ),
    ]
