# Generated by Django 5.0.6 on 2024-06-02 14:02

import general_app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_app', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', general_app.models.CustomUserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
