# Generated by Django 5.0.6 on 2024-06-28 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('segment', '0030_booking_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Out Of Order', 'Out Of order')], default='Active', max_length=15)),
                ('overview', models.TextField()),
                ('featured_image', models.ImageField(upload_to='refuel/images')),
                ('breakfast_opening', models.TimeField()),
                ('breakfast_closing', models.TimeField()),
                ('lunch_opening', models.TimeField()),
                ('lunch_closing', models.TimeField()),
                ('dinner_opening', models.TimeField()),
                ('dinner_closing', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='segment.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='refuel/images')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refuel.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantCuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refuel.cuisine')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuisines', to='refuel.restaurant')),
            ],
        ),
    ]
