# Generated by Django 5.0.6 on 2024-06-28 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refuel', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='restaurantcuisine',
            unique_together={('restaurant', 'cuisine')},
        ),
    ]
