# Generated by Django 5.0.6 on 2024-06-28 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refuel', '0002_alter_restaurantcuisine_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='discount_in_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
