# Generated by Django 5.0.6 on 2024-06-28 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refuel', '0004_reservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='guest_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='guest_name',
            new_name='name',
        ),
    ]
