# Generated by Django 5.0.6 on 2024-06-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refuel', '0005_rename_guest_email_reservation_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='total_bill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
