# Generated by Django 5.0.6 on 2024-07-02 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refuel', '0007_gender_gym_gymgallery_gymgender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymgender',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refuel.gender'),
        ),
        migrations.AlterField(
            model_name='gymgender',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gender_allowance', to='refuel.gym'),
        ),
    ]
