# Generated by Django 5.0.6 on 2024-07-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refuel', '0010_gymmembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymmembership',
            name='additional_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
